[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32@6.3.2
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  madhephaestus/ESP32Servo
